package com.flj.student_system.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_academy
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAcademy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.academy_id
     *
     * @mbg.generated
     */
    private Integer academyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.academy_name
     *
     * @mbg.generated
     */
    private String academyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.id
     *
     * @return the value of t_academy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.id
     *
     * @param id the value for t_academy.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.academy_id
     *
     * @return the value of t_academy.academy_id
     *
     * @mbg.generated
     */
    public Integer getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.academy_id
     *
     * @param academyId the value for t_academy.academy_id
     *
     * @mbg.generated
     */
    public void setAcademyId(Integer academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.academy_name
     *
     * @return the value of t_academy.academy_name
     *
     * @mbg.generated
     */
    public String getAcademyName() {
        return academyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.academy_name
     *
     * @param academyName the value for t_academy.academy_name
     *
     * @mbg.generated
     */
    public void setAcademyName(String academyName) {
        this.academyName = academyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.mark
     *
     * @return the value of t_academy.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.mark
     *
     * @param mark the value for t_academy.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}