package com.flj.student_system.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_academy_class
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAcademyClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy_class.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy_class.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy_class.academy_id
     *
     * @mbg.generated
     */
    private Integer academyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy_class.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy_class.id
     *
     * @return the value of t_academy_class.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy_class.id
     *
     * @param id the value for t_academy_class.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy_class.class_id
     *
     * @return the value of t_academy_class.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy_class.class_id
     *
     * @param classId the value for t_academy_class.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy_class.academy_id
     *
     * @return the value of t_academy_class.academy_id
     *
     * @mbg.generated
     */
    public Integer getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy_class.academy_id
     *
     * @param academyId the value for t_academy_class.academy_id
     *
     * @mbg.generated
     */
    public void setAcademyId(Integer academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy_class.mark
     *
     * @return the value of t_academy_class.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy_class.mark
     *
     * @param mark the value for t_academy_class.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}