package com.flj.student_system.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_dormitory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TDormitory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_num
     *
     * @mbg.generated
     */
    private Integer dormitoryNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.dormitory_addr
     *
     * @mbg.generated
     */
    private String dormitoryAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.people_plan
     *
     * @mbg.generated
     */
    private Integer peoplePlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dormitory.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.id
     *
     * @return the value of t_dormitory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.id
     *
     * @param id the value for t_dormitory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_num
     *
     * @return the value of t_dormitory.dormitory_num
     *
     * @mbg.generated
     */
    public Integer getDormitoryNum() {
        return dormitoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_num
     *
     * @param dormitoryNum the value for t_dormitory.dormitory_num
     *
     * @mbg.generated
     */
    public void setDormitoryNum(Integer dormitoryNum) {
        this.dormitoryNum = dormitoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.dormitory_addr
     *
     * @return the value of t_dormitory.dormitory_addr
     *
     * @mbg.generated
     */
    public String getDormitoryAddr() {
        return dormitoryAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.dormitory_addr
     *
     * @param dormitoryAddr the value for t_dormitory.dormitory_addr
     *
     * @mbg.generated
     */
    public void setDormitoryAddr(String dormitoryAddr) {
        this.dormitoryAddr = dormitoryAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.people_plan
     *
     * @return the value of t_dormitory.people_plan
     *
     * @mbg.generated
     */
    public Integer getPeoplePlan() {
        return peoplePlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.people_plan
     *
     * @param peoplePlan the value for t_dormitory.people_plan
     *
     * @mbg.generated
     */
    public void setPeoplePlan(Integer peoplePlan) {
        this.peoplePlan = peoplePlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dormitory.mark
     *
     * @return the value of t_dormitory.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dormitory.mark
     *
     * @param mark the value for t_dormitory.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}