package com.flj.student_system.entity;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_repairs
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TRepairs {

    @ApiModelProperty(value = "主键id")
    private Integer id;

    @ApiModelProperty(value = "宿舍号")
    private Integer dormitoryNum;

    @ApiModelProperty(value = "报修时间")
    private Date repairsTime;

    @ApiModelProperty(value = "报修问题")
    private String problem;

    @ApiModelProperty(value = "报修状态")
    private Byte state;

    @ApiModelProperty(value = "备注")
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repairs.id
     *
     * @return the value of t_repairs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repairs.id
     *
     * @param id the value for t_repairs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repairs.dormitory_num
     *
     * @return the value of t_repairs.dormitory_num
     *
     * @mbg.generated
     */
    public Integer getDormitoryNum() {
        return dormitoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repairs.dormitory_num
     *
     * @param dormitoryNum the value for t_repairs.dormitory_num
     *
     * @mbg.generated
     */
    public void setDormitoryNum(Integer dormitoryNum) {
        this.dormitoryNum = dormitoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repairs.repairs_time
     *
     * @return the value of t_repairs.repairs_time
     *
     * @mbg.generated
     */
    public Date getRepairsTime() {
        return repairsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repairs.repairs_time
     *
     * @param repairsTime the value for t_repairs.repairs_time
     *
     * @mbg.generated
     */
    public void setRepairsTime(Date repairsTime) {
        this.repairsTime = repairsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repairs.problem
     *
     * @return the value of t_repairs.problem
     *
     * @mbg.generated
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repairs.problem
     *
     * @param problem the value for t_repairs.problem
     *
     * @mbg.generated
     */
    public void setProblem(String problem) {
        this.problem = problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repairs.state
     *
     * @return the value of t_repairs.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repairs.state
     *
     * @param state the value for t_repairs.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_repairs.mark
     *
     * @return the value of t_repairs.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_repairs.mark
     *
     * @param mark the value for t_repairs.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}