package com.flj.student_system.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_role_home
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TRoleHome {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_home.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_home.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_home.href
     *
     * @mbg.generated
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_home.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_home.id
     *
     * @return the value of t_role_home.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_home.id
     *
     * @param id the value for t_role_home.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_home.title
     *
     * @return the value of t_role_home.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_home.title
     *
     * @param title the value for t_role_home.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_home.href
     *
     * @return the value of t_role_home.href
     *
     * @mbg.generated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_home.href
     *
     * @param href the value for t_role_home.href
     *
     * @mbg.generated
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_home.mark
     *
     * @return the value of t_role_home.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_home.mark
     *
     * @param mark the value for t_role_home.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    @Override
    public String toString() {
        return "TRoleHome{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", href='" + href + '\'' +
                ", mark='" + mark + '\'' +
                '}';
    }
}