package com.flj.student_system.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_role_router
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TRoleRouter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_router.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_router.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_router.homeInfo
     *
     * @mbg.generated
     */
    private Integer homeinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_router.logoInfo
     *
     * @mbg.generated
     */
    private Integer logoinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_router.menuInfo
     *
     * @mbg.generated
     */
    private Integer menuinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_router.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_router.id
     *
     * @return the value of t_role_router.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_router.id
     *
     * @param id the value for t_role_router.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_router.role_id
     *
     * @return the value of t_role_router.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_router.role_id
     *
     * @param roleId the value for t_role_router.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_router.homeInfo
     *
     * @return the value of t_role_router.homeInfo
     *
     * @mbg.generated
     */
    public Integer getHomeinfo() {
        return homeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_router.homeInfo
     *
     * @param homeinfo the value for t_role_router.homeInfo
     *
     * @mbg.generated
     */
    public void setHomeinfo(Integer homeinfo) {
        this.homeinfo = homeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_router.logoInfo
     *
     * @return the value of t_role_router.logoInfo
     *
     * @mbg.generated
     */
    public Integer getLogoinfo() {
        return logoinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_router.logoInfo
     *
     * @param logoinfo the value for t_role_router.logoInfo
     *
     * @mbg.generated
     */
    public void setLogoinfo(Integer logoinfo) {
        this.logoinfo = logoinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_router.menuInfo
     *
     * @return the value of t_role_router.menuInfo
     *
     * @mbg.generated
     */
    public Integer getMenuinfo() {
        return menuinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_router.menuInfo
     *
     * @param menuinfo the value for t_role_router.menuInfo
     *
     * @mbg.generated
     */
    public void setMenuinfo(Integer menuinfo) {
        this.menuinfo = menuinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_router.mark
     *
     * @return the value of t_role_router.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_router.mark
     *
     * @param mark the value for t_role_router.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}