package com.flj.student_system.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_student
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_num
     *
     * @mbg.generated
     */
    private Long studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   0表示男生，
     *   1表示女生
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.sex
     *
     * @mbg.generated
     */
    private byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.home_address
     *
     * @mbg.generated
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.dormitory_num
     *
     * @mbg.generated
     */
    private Integer dormitoryNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.phone
     *
     * @mbg.generated
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_num
     *
     * @return the value of t_student.student_num
     *
     * @mbg.generated
     */
    public Long getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_num
     *
     * @param studentNum the value for t_student.student_num
     *
     * @mbg.generated
     */
    public void setStudentNum(Long studentNum) {
        this.studentNum = studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.sex
     *
     * @return the value of t_student.sex
     *
     * @mbg.generated
     */
    public byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.sex
     *
     * @param sex the value for t_student.sex
     *
     * @mbg.generated
     */
    public void setSex(byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.home_address
     *
     * @return the value of t_student.home_address
     *
     * @mbg.generated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.home_address
     *
     * @param homeAddress the value for t_student.home_address
     *
     * @mbg.generated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.dormitory_num
     *
     * @return the value of t_student.dormitory_num
     *
     * @mbg.generated
     */
    public Integer getDormitoryNum() {
        return dormitoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.dormitory_num
     *
     * @param dormitoryNum the value for t_student.dormitory_num
     *
     * @mbg.generated
     */
    public void setDormitoryNum(Integer dormitoryNum) {
        this.dormitoryNum = dormitoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.class_id
     *
     * @return the value of t_student.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.class_id
     *
     * @param classId the value for t_student.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.phone
     *
     * @return the value of t_student.phone
     *
     * @mbg.generated
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.phone
     *
     * @param phone the value for t_student.phone
     *
     * @mbg.generated
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.password
     *
     * @return the value of t_student.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.password
     *
     * @param password the value for t_student.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.mark
     *
     * @return the value of t_student.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.mark
     *
     * @param mark the value for t_student.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}