# 配置数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/student_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

# 配置mybatis的xml文件和实体类别名
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.flj.student_system.entity
