package com.flj.student_system.dao;

import com.flj.student_system.entity.TAcademy;

import java.util.List;

public interface TAcademyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int insert(TAcademy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int insertSelective(TAcademy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    TAcademy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAcademy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAcademy record);

    /*
    * 根据学院ID查询学院名称
    * */
    String selectByAcademyClassId(Integer academyClassId);


    /*
    * 查询所有学院信息
    * */
    List<TAcademy> selectAllTAcademy();
}