package com.flj.student_system.dao;

import com.flj.student_system.entity.TAcademy;

public interface TAcademyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int insert(TAcademy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int insertSelective(TAcademy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    TAcademy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAcademy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAcademy record);
}