package com.flj.student_system.dao;

import com.flj.student_system.entity.TChoseCourse;
import com.flj.student_system.entity.TCourse;
import com.flj.student_system.entity.form.ChoseCouseFrom;
import com.flj.student_system.entity.form.StudentCourseForm;

import java.util.List;

public interface TChoseCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chose_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chose_course
     *
     * @mbg.generated
     */
    int insert(TChoseCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chose_course
     *
     * @mbg.generated
     */
    int insertSelective(TChoseCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chose_course
     *
     * @mbg.generated
     */
    TChoseCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chose_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TChoseCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chose_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TChoseCourse record);

    /*
    * 选课
    * */
    int choseCouese(ChoseCouseFrom choseCouseFrom);

    /*
    * 退选课程
    * */
    int quitCourse(ChoseCouseFrom choseCouseFrom);

    /*
    * 打分
    * */
    int mark(ChoseCouseFrom choseCouseFrom);

    /*
    * 查询所学课程及分数
    * */
    List<TCourse> selectByStudentNum(Long studentNum);

    /*
    * 查看某个课程有哪些学生选
    * */
    List<StudentCourseForm> selectsStudentByCourseId(Integer courseId);
}