package com.flj.student_system.dao;

import com.flj.student_system.entity.TClassAndGrade;

import java.util.List;

public interface TClassAndGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_and_grade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_and_grade
     *
     * @mbg.generated
     */
    int insert(TClassAndGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_and_grade
     *
     * @mbg.generated
     */
    int insertSelective(TClassAndGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_and_grade
     *
     * @mbg.generated
     */
    TClassAndGrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_and_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TClassAndGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_and_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TClassAndGrade record);

    /*
    * 根据班级ID查班级名称
    * */
    String selectByClassId(Integer classId);

    /*
    * 查询所有班级
    * */
    List<TClassAndGrade> selectAllClass();
}