package com.flj.student_system.dao;

import com.flj.student_system.entity.TCourse;
import com.flj.student_system.entity.form.CourseForm;

import java.util.List;

public interface TCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated
     */
    int insert(TCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated
     */
    int insertSelective(TCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated
     */
    TCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourse record);

    /*
     * 查询所有课程信息
     * */
    List<TCourse> selectAllCourse();

    /*
    * 插入课程
    * */
    int insertOneCourse(CourseForm courseForm);

    /*
    * 查询某个教师所教的课程
    * */
    List<TCourse> selectCourseByTeacherId(Integer teacherId);
}