package com.flj.student_system.dao;

import com.flj.student_system.entity.TRoleLogin;

public interface TRoleLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_login
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_login
     *
     * @mbg.generated
     */
    int insert(TRoleLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_login
     *
     * @mbg.generated
     */
    int insertSelective(TRoleLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_login
     *
     * @mbg.generated
     */
    TRoleLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_login
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TRoleLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_login
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TRoleLogin record);
}