package com.flj.student_system.dao;

import com.flj.student_system.entity.TRoleHome;

public interface TRoleHomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_home
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_home
     *
     * @mbg.generated
     */
    int insert(TRoleHome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_home
     *
     * @mbg.generated
     */
    int insertSelective(TRoleHome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_home
     *
     * @mbg.generated
     */
    TRoleHome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_home
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TRoleHome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_home
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TRoleHome record);
}