package com.flj.student_system.dao;

import com.flj.student_system.entity.TRouterMenu;

public interface TRouterMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_router_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_router_menu
     *
     * @mbg.generated
     */
    int insert(TRouterMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_router_menu
     *
     * @mbg.generated
     */
    int insertSelective(TRouterMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_router_menu
     *
     * @mbg.generated
     */
    TRouterMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_router_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TRouterMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_router_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TRouterMenu record);


}