package com.flj.student_system.dao;

import com.flj.student_system.entity.TStudent;
import com.flj.student_system.entity.form.StudentForm;

import java.util.List;

public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int insertSelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    TStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TStudent record);

    /*
    * 查询所有学生
    * */
    List<TStudent> selectAllStudent();

    /*
    * 插入某个学生
    * */
    int insertOneStudent(StudentForm studentForm);

    /*
    * 查询旧密码
    * */
    String selectOldPassword(long num);

    /*
    * 更新
    * */
    int updateByStudentNumSelective(TStudent tStudent);

    /*
    * 查询学生是否存在
    * */
    int selectIfOrNotExists(Integer peopleId);

    /*
    * 修改密码
    * */
    int selectCheckPassword(Integer peopleId, String password);
}