package com.flj.student_system.dao;

import com.flj.student_system.entity.TStudent;
import com.flj.student_system.entity.form.StudentForm;

import java.util.List;

public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int insertSelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    TStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TStudent record);

    /*
     * 查询所有学生
     * */
    List<TStudent> selectAllStudent();

    /*
    * 新增学生
    * */
    int insertOneStudent(StudentForm studentForm);

    /*
    * 查询旧密码
    * */
    String selectOldPassword(long studentNum);

    /*
    * 根据学号修改信息
    * */
    int updateByStudentNumSelective(TStudent tStudent);
}